### ISSUE TITLE
Simplify stop script

### ISSUE THREAD

**Issue by intentionally-left-nil** [shmalex/openvpn3_manager#1]
Instead of having a python script to get the path, you could do something like this
```
 openvpn3 sessions-list | grep Path | awk -v OFS='\t' '{print $2}' | while read -r path; do
    openvpn3 session-manage --path "$path" --disconnect
done
```

**Comment by shmalex** [comment]
Hi @AnilRedshift , thank you for your idea, it's looks awesome! In that small project i was practising the output steam from python.
I will make sure to add your idea to repo. Thanks!

https://github.com/shmalex/openvpn3_manager/commit/4f500ffcaa2fd0d306edc51a91b18453ae31c9b8
